### ISSUE TITLE
DC during scanning

### ISSUE THREAD

**Issue by gaveer** [AcidWeb/RECrystallize#2]
Hello there , i keep getting DC during scanning everytime i scan , i tried to use 
`/run RECrystallize.Config.ScanStep = 20` and still keep getting dc 
Kazzak Server 
Ace3 loaded

**Comment by AcidWeb** [comment]
Yes. I'm aware. Some people get them. Users of Linux even more often.

Currently I'm contacting Blizzard in attempt to clarify this matter.

**Comment by gaveer** [comment]
anyway around it so i not getting dcd
